# vim:fileencoding=utf-8:foldmethod=marker

#: ZSH Initialisation {{{

export PATH=$HOME/.local/bin:$PATH
eval "$(starship init zsh)"
eval $(thefuck --alias fuck)

#: }}}

#: Zinit Imports (with Turbo) {{{

source ~/.zinit/bin/zinit.zsh
zinit wait lucid blockf for \
    atinit"zicompinit; zicdreplay" \    # Fast compinit startup
    atload"_zsh_autosuggest_start" \    # Start zsh-autosuggestions immediately
    zsh-users/zsh-autosuggestions \ # Autosuggestions
    zdharma/fast-syntax-highlighting \  # Syntax highlighting
source ~/.aliases.zsh   # local-aliases.zsh file which contains local aliases

#: }}}

#: Shell Variables {{{

export EDITOR=nvim

#: }}}

#: Aliases {{{

#: Suffix Aliases {{{

alias -s txt=nvim
alias -s tex=nvim
alias -s json=nvim
alias -s md=mdcat
alias -s markdown=mdcat
alias -s pdf=okular
alias -s html=firefox
alias -s ipnyb=euphorie
alias -s zip=unzip
alias -s tar=tar -xvf
alias -s tar.gz=tar -xvzf

#: Media Suffix Aliases: {{{

alias -s gif=nomacs
alias -s bmp=nomacs
alias -s ico=nomacs
alias -s raw=nomacs
alias -s dng=nomacs
alias -s png=nomacs
alias -s jpeg=nomacs
alias -s jpg=nomacs
alias -s svg=nomacs
alias -s mp3=vlc
alias -s mp4=vlc
alias -s mkv=vlc
alias -s mov=vlc
alias -s flv=vlc
alias -s mpeg=vlc
alias -s mpg=vlc
alias -s avi=vlc

#: }}}

#: Languages Suffix Aliases: {{{

alias -s sh=bash
alias -s bash=bash
alias -s py=python
alias -s rb=ruby
alias -s ruby=ruby
alias -s go=go
alias -s java=javac
alias -s class=java
alias -s jar=java
alias -s js=node
alias -s lua=lua
alias -s perl=perl
alias -s pl=perl
alias -s ps1=powershell
alias -s psd1=powershell
alias -s psm1=powershell

#: }}}

#: }}}

#: Kitty Aliases {{{

alias icat="kitty +kitten icat"
alias kdiff="kitty +kitten diff"

#: }}}

#: Directory Aliases {{{

alias ls='exa --icons'
alias lsa='exa -a --icons'
alias ll='exa --long --git --icons'
alias lla='exa --long -a --git --icons'
alias lr='exa --recurse --icons'
alias lg='exa -lg --git --icons'
alias lga='exa -lga --git --icons'
alias tree='exa --tree --icons'
alias md='mkdir -p'
alias rd='rmdir'
alias -g ...='../..'
alias -g ....='../../..'
alias -g .....='../../../..'
alias -g ......='../../../../..'
alias -g .......='../../../../../..'
alias -g ........='../../../../../../..'

#: }}}

#: Git Aliases {{{

alias g='git'
alias gs='git status'
alias gp='git push'
alias gpl='git pull'
alias ga='git add'
alias glg='git log --graph --oneline --decorate'
alias gd='git diff'

#: }}}

#: System Alt Tool Aliases {{{

alias cat="bat"
alias du="dust"
alias df="duf"
alias top="bottom"
alias htop="bottom"
alias ping="gping"
alias ps="procs"

#: }}}

#: Program Aliases {{{

alias python="python3"
alias jv="java"
alias vim="nvim"
alias docker="sudo docker"

#: }}}

#: Media Aliases {{{

alias yt-dl="yt-dlp"
alias ytdl="yt-dlp"
alias ytdlp="yt-dlp"
alias ytmp4="yt-dlp --merge-output-format mp4"
alias ytdla="yt-dlp --extract audio"
alias ytdlpa="yt-dlp --extract-audio"
alias yt-dla="yt-dlp --extract-audio"
alias yt-dlpa="yt-dlp --extract-audio"
alias ytmp3="yt-dlp --extract-audio --audio-format mp3"

#: }}}

#: Miscellaneous Aliases {{{
alias -g gpg="qubes-gpg-client-wrapper"
alias volume="amixer sset 'Master'"
alias sign='gpg --detach-sign --armor'
alias grep='grep --color'
alias ssh='TERM=xterm-256color ssh'
alias myip="curl ifconfig.io"
alias lip="ifconfig | grep -e 'eth0' -e 'enX0' -A1 | tail -n1 | awk '{print \$2}' | cut -f1  -d'/'"
alias vip="ifconfig | grep 'tun0' -A1 | tail -n1 | awk '{print \$2}' | cut -f1  -d'/'"
alias tgz="tar -xvfz"
alias qc='qvm-copy-to-vm'
alias qm='qvm-move-to-vm'
alias speedtest='curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python -'
alias timestamp='date --iso-8601=seconds'

#: }}}

#: }}}

#: Functions {{{

function copy() {
    xclip -i $1 -sel clip
}

#: }}}

#: Themeing {{{

#: p10k {{{

source ~/powerlevel10k/powerlevel10k.zsh-theme
ZSH_THEME="powerlevel10k/powerlevel10k"
typeset -g POWERLEVEL9k_INSTANT_PROMPT=off

#: }}}


#: }}}
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
discocss
export QUBES_GPG_DOMAIN=gpg
